### ISSUE TITLE
WINNER: Connect function failed with error: 10060

### ISSUE THREAD

**Issue by HyperCriSiS** [dawallet/burstwindowswallet#6]
Hi,

I don't get any profit through mining.
These are the messages in the console:

23:14:02 New block 370374, baseTarget 607224, netDiff 30178 Tb
23:14:07 Thread "X:\Burst\plots" @ 4.4 sec (23.6 MB/s) CPU 24.87%
WINNER: Connect function failed with error: 10060
23:15:08 New block 370376, baseTarget 675555, netDiff 27126 Tb
23:15:13 Thread "X:\Burst\plots" @ 4.5 sec (23.0 MB/s) CPU 28.68%
WINNER: Connect function failed with error: 10060

Thanks and regards,
Hyper

**Comment by dawallet** [comment]
This is not a client issue. For support of this type I recommend you https://forums.burst-team.us
